CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "salary" money,
  "savings" money
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "current_amount" money,
  "limit" money,
  "name" varchar(50) NOT NULL,
  "user_id" int UNIQUE
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "envelope_id" int UNIQUE,
  "amount" money,
  "timestamp" timestamp
);

ALTER TABLE "categories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("envelope_id") REFERENCES "categories" ("id");
