CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hash" text,
  "salary" money,
  "savings" money,
  "username" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "envelopes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "current_amount" money,
  "envelope_limit" money,
  "name" varchar(50) NOT NULL,
  "user_id" int NOT NULL,
  CONSTRAINT positive_current_amount CHECK ("current_amount" >= '0.00' :: money),
  CONSTRAINT current_amount_within_envelope_limit CHECK ("current_amount" <= "envelope_limit"),
  CONSTRAINT positive_envelope_limit CHECK ("envelope_limit" > '0.00' :: money),
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" money NOT NULL,
  "envelope_id" int NOT NULL,
  "user_id" int NOT NULL,
  "timestamp" timestamp without time zone NOT NULL,
  FOREIGN KEY ("envelope_id") REFERENCES "envelopes" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- Manage users sessions
CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL
) WITH (OIDS = FALSE);

ALTER TABLE
  "session"
ADD
  CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "session" ("expire");