CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hash" text NOT NULL,
  "salary" money,
  "savings" money,
  "username" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "current_amount" money,
  "limit" money,
  "name" varchar(50) NOT NULL,
  "user_id" int UNIQUE
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" money,
  "envelope_id" int UNIQUE,
  "timestamp" timestamp
);

-- Manage users sessions
CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);

ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "session" ("expire");

ALTER TABLE "categories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("envelope_id") REFERENCES "categories" ("id");

INSERT INTO "users" ("username", "hash") VALUES ('username', '123');